// services/multilanguage.js

const multiLanguage = {
    "We're here to help!": {
        en: "We're here to help!",
        uk: "Ми тут, щоб допомогти!",
        pl: "Jesteśmy tutaj, aby pomóc!",
        fr: "Nous sommes là pour vous aider !",
        de: "Wir sind hier, um zu helfen!",
        es: "¡Estamos aquí para ayudar!",
        it: "Siamo qui per aiutarti!",
        pt: "Estamos aqui para ajudar!",
        ro: "Suntem aici să vă ajutăm!",
        fi: "Olemme täällä auttamassa!"
    },
    "Welcome!": {
        en: "Welcome!",
        uk: "Ласкаво просимо!",
        pl: "Witaj!",
        fr: "Bienvenue !",
        de: "Willkommen!",
        es: "¡Bienvenido!",
        it: "Benvenuto!",
        pt: "Bem-vindo!",
        ro: "Bun venit!",
        fi: "Tervetuloa!"
    },
    "Please enter your email address to start a conversation with our support team.": {
        en: "Please enter your email address to start a conversation with our support team.",
        uk: "Будь ласка, введіть свою електронну адресу, щоб розпочати розмову з нашою командою підтримки.",
        pl: "Wprowadź swój adres e-mail, aby rozpocząć rozmowę z naszym zespołem wsparcia.",
        fr: "Veuillez entrer votre adresse e-mail pour démarrer une conversation avec notre équipe d'assistance.",
        de: "Bitte geben Sie Ihre E-Mail-Adresse ein, um eine Unterhaltung mit unserem Support-Team zu beginnen.",
        es: "Por favor, introduce tu dirección de correo electrónico para iniciar una conversación con nuestro equipo de soporte.",
        it: "Inserisci il tuo indirizzo email per iniziare una conversazione con il nostro team di supporto.",
        pt: "Por favor, insira seu endereço de e-mail para iniciar uma conversa com nossa equipe de suporte.",
        ro: "Vă rugăm să introduceți adresa dvs. de e-mail pentru a începe o conversație cu echipa noastră de asistență.",
        fi: "Ole hyvä ja syötä sähköpostiosoitteesi aloittaaksesi keskustelun tukitiimimme kanssa."
    },
    "Enter your email address": {
        en: "Enter your email address",
        uk: "Введіть свою електронну адресу",
        pl: "Wprowadź swój adres e-mail",
        fr: "Entrez votre adresse e-mail",
        de: "Geben Sie Ihre E-Mail-Adresse ein",
        es: "Introduce tu dirección de correo electrónico",
        it: "Inserisci la tua email",
        pt: "Insira seu endereço de e-mail",
        ro: "Introduceți adresa dvs. de e-mail",
        fi: "Syötä sähköpostiosoitteesi"
    },
    "Start Conversation": {
        en: "Start Conversation",
        uk: "Розпочати розмову",
        pl: "Rozpocznij rozmowę",
        fr: "Commencer la conversation",
        de: "Konversation starten",
        es: "Iniciar conversación",
        it: "Inizia conversazione",
        pt: "Iniciar Conversa",
        ro: "Începe conversația",
        fi: "Aloita keskustelu"
    },
    "Your Conversations": {
        en: "Your Conversations",
        uk: "Ваші розмови",
        pl: "Twoje rozmowy",
        fr: "Vos conversations",
        de: "Ihre Konversationen",
        es: "Tus conversaciones",
        it: "Le tue conversazioni",
        pt: "Suas Conversas",
        ro: "Conversațiile tale",
        fi: "Keskustelusi"
    },
    "Select a chat or start new one": {
        en: "Select a chat or start new one",
        uk: "Виберіть чат або розпочніть новий",
        pl: "Wybierz czat lub rozpocznij nowy",
        fr: "Sélectionnez un chat ou commencez-en un nouveau",
        de: "Wählen Sie einen Chat oder starten Sie einen neuen",
        es: "Selecciona un chat o inicia uno nuevo",
        it: "Seleziona una chat o iniziane una nuova",
        pt: "Selecione um chat ou inicie um novo",
        ro: "Selectați o conversație sau începeți una nouă",
        fi: "Valitse keskustelu tai aloita uusi"
    },
    "No conversations yet": {
        en: "No conversations yet",
        uk: "Ще немає розмов",
        pl: "Brak rozmów",
        fr: "Aucune conversation pour l'instant",
        de: "Noch keine Konversationen",
        es: "Aún no hay conversaciones",
        it: "Nessuna conversazione ancora",
        pt: "Nenhuma conversa ainda",
        ro: "Încă nu sunt conversații",
        fi: "Ei vielä keskusteluja"
    },
    "Click \"Start New Conversation\" to begin!": {
        en: "Click \"Start New Conversation\" to begin!",
        uk: "Натисніть «Розпочати нову розмову», щоб почати!",
        pl: "Kliknij „Rozpocznij nową rozmowę”, aby zacząć!",
        fr: "Cliquez sur « Démarrer une nouvelle conversation » pour commencer !",
        de: "Klicken Sie auf „Neue Konversation starten“, um zu beginnen!",
        es: "¡Haz clic en \"Iniciar nueva conversación\" para empezar!",
        it: "Clicca su \"Inizia nuova conversazione\" per iniziare!",
        pt: "Clique em \"Iniciar Nova Conversa\" para começar!",
        ro: "Faceți clic pe „Începeți o conversație nouă” pentru a începe!",
        fi: "Aloita napsauttamalla \"Aloita uusi keskustelu\"!"
    },
    "Created:": {
        en: "Created:",
        uk: "Створено:",
        pl: "Utworzono:",
        fr: "Créé le :",
        de: "Erstellt:",
        es: "Creado:",
        it: "Creato il:",
        pt: "Criado em:",
        ro: "Creat la:",
        fi: "Luotu:"
    },
    "Last Update:": {
        en: "Last Update:",
        uk: "Останнє оновлення:",
        pl: "Ostatnia aktualizacja:",
        fr: "Dernière mise à jour :",
        de: "Letzte Aktualisierung:",
        es: "Última actualización:",
        it: "Ultimo aggiornamento:",
        pt: "Última atualização:",
        ro: "Ultima actualizare:",
        fi: "Viimeksi päivitetty:"
    },
    "Click to view conversation": {
        en: "Click to view conversation",
        uk: "Натисніть, щоб переглянути розмову",
        pl: "Kliknij, aby wyświetlić rozmowę",
        fr: "Cliquez pour voir la conversation",
        de: "Klicken Sie, um die Konversation anzuzeigen",
        es: "Haz clic para ver la conversación",
        it: "Clicca per visualizzare la conversazione",
        pt: "Clique para ver a conversa",
        ro: "Faceți clic pentru a vedea conversația",
        fi: "Napsauta nähdäksesi keskustelun"
    },
    "✨ Start New Conversation": {
        en: "✨ Start New Conversation",
        uk: "✨ Розпочати нову розмову",
        pl: "✨ Rozpocznij nową rozmowę",
        fr: "✨ Démarrer une nouvelle conversation",
        de: "✨ Neue Konversation starten",
        es: "✨ Iniciar nueva conversación",
        it: "✨ Inizia nuova conversazione",
        pt: "✨ Iniciar Nova Conversa",
        ro: "✨ Începeți o conversație nouă",
        fi: "✨ Aloita uusi keskustelu"
    },
    "Live Chat": {
        en: "Live Chat",
        uk: "Онлайн чат",
        pl: "Czat na żywo",
        fr: "Chat en direct",
        de: "Live-Chat",
        es: "Chat en vivo",
        it: "Chat dal vivo",
        pt: "Chat ao vivo",
        ro: "Chat live",
        fi: "Live-chat"
    },
    "Connected with support": {
        en: "Connected with support",
        uk: "Підключено до підтримки",
        pl: "Połączono ze wsparciem",
        fr: "Connecté avec le support",
        de: "Mit dem Support verbunden",
        es: "Conectado con soporte",
        it: "Connesso con il supporto",
        pt: "Conectado com o suporte",
        ro: "Conectat cu asistența",
        fi: "Yhdistetty tukeen"
    },
    "Support Team": {
        en: "Support Team",
        uk: "Команда підтримки",
        pl: "Zespół wsparcia",
        fr: "Équipe de support",
        de: "Support-Team",
        es: "Equipo de soporte",
        it: "Team di supporto",
        pt: "Equipe de Suporte",
        ro: "Echipa de asistență",
        fi: "Tukitiimi"
    },
    "Type your message...": {
        en: "Type your message...",
        uk: "Введіть своє повідомлення...",
        pl: "Wpisz swoją wiadomość...",
        fr: "Tapez votre message...",
        de: "Geben Sie Ihre Nachricht ein...",
        es: "Escribe tu mensaje...",
        it: "Scrivi il tuo messaggio...",
        pt: "Digite sua mensagem...",
        ro: "Scrieți mesajul dvs...",
        fi: "Kirjoita viestisi..."
    },
    "Send": {
        en: "Send",
        uk: "Надіслати",
        pl: "Wyślij",
        fr: "Envoyer",
        de: "Senden",
        es: "Enviar",
        it: "Invia",
        pt: "Enviar",
        ro: "Trimite",
        fi: "Lähetä"
    },
    "You": {
        en: "You",
        uk: "Ви",
        pl: "Ty",
        fr: "Vous",
        de: "Sie",
        es: "Tú",
        it: "Tu",
        pt: "Você",
        ro: "Tu",
        fi: "Sinä"
    },
    "Bot": {
        en: "Bot",
        uk: "Бот",
        pl: "Bot",
        fr: "Robot",
        de: "Bot",
        es: "Bot",
        it: "Bot",
        pt: "Bot",
        ro: "Robot",
        fi: "Botti"
    },
    "AI Assistant": {
        en: "AI Assistant",
        uk: "АІ Асистент",
        pl: "Asystent AI",
        fr: "Assistant IA",
        de: "KI-Assistent",
        es: "Asistente de IA",
        it: "Assistente AI",
        pt: "Assistente de IA",
        ro: "Asistent AI",
        fi: "Tekoälyavustaja"
    },
    "Owner": {
        en: "Owner",
        uk: "Власник",
        pl: "Właściciel",
        fr: "Propriétaire",
        de: "Besitzer",
        es: "Propietario",
        it: "Proprietario",
        pt: "Proprietário",
        ro: "Proprietar",
        fi: "Omistaja"
    },
    "Error loading chat history.": {
        en: "Error loading chat history.",
        uk: "Помилка завантаження історії чату.",
        pl: "Błąd ładowania historii czatu.",
        fr: "Erreur lors du chargement de l'historique du chat.",
        de: "Fehler beim Laden des Chatverlaufs.",
        es: "Error al cargar el historial del chat.",
        it: "Errore durante il caricamento della cronologia chat.",
        pt: "Erro ao carregar o histórico de conversas.",
        ro: "Eroare la încărcarea istoricului conversațiilor.",
        fi: "Virhe keskusteluhistorian lataamisessa."
    },
    "Error loading your chats.": {
        en: "Error loading your chats.",
        uk: "Помилка завантаження ваших чатів.",
        pl: "Błąd ładowania twoich czatów.",
        fr: "Erreur lors du chargement de vos chats.",
        de: "Fehler beim Laden Ihrer Chats.",
        es: "Error al cargar tus chats.",
        it: "Errore durante il caricamento delle tue chat.",
        pt: "Erro ao carregar suas conversas.",
        ro: "Eroare la încărcarea conversațiilor dvs.",
        fi: "Virhe keskustelujesi lataamisessa."
    },
    "Error starting a new chat.": {
        en: "Error starting a new chat.",
        uk: "Помилка при створенні нового чату.",
        pl: "Błąd podczas rozpoczynania nowego czatu.",
        fr: "Erreur lors du démarrage d'un nouveau chat.",
        de: "Fehler beim Starten eines neuen Chats.",
        es: "Error al iniciar un nuevo chat.",
        it: "Errore durante l'avvio di una nuova chat.",
        pt: "Erro ao iniciar um novo chat.",
        ro: "Eroare la pornirea unei conversații noi.",
        fi: "Virhe uuden keskustelun aloittamisessa."
    },
    "This conversation has been closed.": {
        en: "This conversation has been closed.",
        uk: "Цю розмову було закрито.",
        pl: "Ta rozmowa została zamknięta.",
        fr: "Cette conversation a été fermée.",
        de: "Diese Konversation wurde geschlossen.",
        es: "Esta conversación ha sido cerrada.",
        it: "Questa conversazione è stata chiusa.",
        pt: "Esta conversa foi encerrada.",
        ro: "Această conversație a fost închisă.",
        fi: "Tämä keskustelu on suljettu."
    },
    "Hi! What is your name?": {
        "en": "Hi! What is your name?",
        "uk": "Привіт! Як вас звати?",
        "pl": "Cześć! Jak masz na imię?",
        "fr": "Salut ! Comment tu t'appelles ?",
        "de": "Hallo! Wie heißt du?",
        "es": "¡Hola! ¿Cómo te llamas?",
        "it": "Ciao! Come ti chiami?",
        "pt": "Oi! Qual é o seu nome?",
        "ro": "Salut! Cum te numești?",
        "fi": "Hei! Mikä sinun nimesi on?"
    },
    "open": {
        en: "OPEN",
        uk: "ВІДКРИТИ",
        pl: "OTWÓRZ",
        fr: "OUVRIR",
        de: "ÖFFNEN",
        es: "ABRIR",
        it: "APRI",
        pt: "ABRIR",
        ro: "DESCHIDE",
        fi: "AVAA"
    },
    "closed": {
        en: "CLOSED",
        uk: "ЗАКРИТО",
        pl: "ZAMKNIĘTE",
        fr: "FERMÉ",
        de: "GESCHLOSSEN",
        es: "CERRADO",
        it: "CHIUSO",
        pt: "FECHADO",
        ro: "ÎNCHIS",
        fi: "SULJETTU"
    },
    // NEW TEXT ELEMENT
    "Please choose an option to continue.": {
        en: "Please choose an option to continue.",
        uk: "Будь ласка, виберіть варіант для продовження.",
        pl: "Proszę wybrać opcję, aby kontynuować.",
        fr: "Veuillez choisir une option pour continuer.",
        de: "Bitte wählen Sie eine Option, um fortzufahren.",
        es: "Por favor, elige una opción para continuar.",
        it: "Per favore, scegli un'opzione per continuare.",
        pt: "Por favor, escolha uma opção para continuar.",
        ro: "Vă rugăm să alegeți o opțiune pentru a continua.",
        fi: "Ole hyvä ja valitse vaihtoehto jatkaaksesi."
    }
};

export default multiLanguage;